/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ParticipantRecord = IDL.Record({
  'age' : IDL.Nat,
  'occupation' : IDL.Text,
  'improvement' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
  'education' : IDL.Text,
  'gender' : IDL.Text,
  'smokingStatus' : IDL.Text,
  'tbContactHistory' : IDL.Text,
  'registrationId' : IDL.Text,
  'dateTime' : IDL.Text,
  'riskLevel' : IDL.Opt(IDL.Text),
  'preTestScore' : IDL.Opt(IDL.Nat),
  'postTestScore' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllParticipants' : IDL.Func([], [IDL.Vec(ParticipantRecord)], ['query']),
  'getAverageImprovement' : IDL.Func([], [IDL.Float64], ['query']),
  'getAveragePostTestScore' : IDL.Func([], [IDL.Float64], ['query']),
  'getAveragePreTestScore' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHighRiskCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getParticipant' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ParticipantRecord)],
      ['query'],
    ),
  'getTotalParticipants' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerParticipant' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePostTestScore' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'savePreTestScore' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
  'saveRiskLevel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ParticipantRecord = IDL.Record({
    'age' : IDL.Nat,
    'occupation' : IDL.Text,
    'improvement' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
    'education' : IDL.Text,
    'gender' : IDL.Text,
    'smokingStatus' : IDL.Text,
    'tbContactHistory' : IDL.Text,
    'registrationId' : IDL.Text,
    'dateTime' : IDL.Text,
    'riskLevel' : IDL.Opt(IDL.Text),
    'preTestScore' : IDL.Opt(IDL.Nat),
    'postTestScore' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllParticipants' : IDL.Func(
        [],
        [IDL.Vec(ParticipantRecord)],
        ['query'],
      ),
    'getAverageImprovement' : IDL.Func([], [IDL.Float64], ['query']),
    'getAveragePostTestScore' : IDL.Func([], [IDL.Float64], ['query']),
    'getAveragePreTestScore' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHighRiskCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getParticipant' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ParticipantRecord)],
        ['query'],
      ),
    'getTotalParticipants' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerParticipant' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePostTestScore' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'savePreTestScore' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Bool], []),
    'saveRiskLevel' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };