/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ParticipantRecord {
  'age' : bigint,
  'occupation' : string,
  'improvement' : [] | [bigint],
  'name' : string,
  'education' : string,
  'gender' : string,
  'smokingStatus' : string,
  'tbContactHistory' : string,
  'registrationId' : string,
  'dateTime' : string,
  'riskLevel' : [] | [string],
  'preTestScore' : [] | [bigint],
  'postTestScore' : [] | [bigint],
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllParticipants' : ActorMethod<[], Array<ParticipantRecord>>,
  'getAverageImprovement' : ActorMethod<[], number>,
  'getAveragePostTestScore' : ActorMethod<[], number>,
  'getAveragePreTestScore' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHighRiskCount' : ActorMethod<[], bigint>,
  'getParticipant' : ActorMethod<[string], [] | [ParticipantRecord]>,
  'getTotalParticipants' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerParticipant' : ActorMethod<
    [string, bigint, string, string, string, string, string, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePostTestScore' : ActorMethod<[string, bigint], boolean>,
  'savePreTestScore' : ActorMethod<[string, bigint], boolean>,
  'saveRiskLevel' : ActorMethod<[string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];